name: Unit Tests
# This workflow runs unit tests on pull requests to ensure code quality.
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - run: npm ci
      - run: npm run test